from spare import Spare21Norm
from spare import Spare1Norm
from spare import SpareCauthyNorm
from norm import norm2vec
from norm import norm1vec
from norm import normInfvec
from norm import normNeInfvec
from norm import normPvec
from norm import norm2mat
from norm import norm1mat
from norm import normInfmat
from norm import normFrobeniusmat
from norm import normNuclearmat
from norm import norm
from norm import norm_compute